import { Inter } from "next/font/google";
import "@/styles//globals.css";
import SessionProvider from "@/providers/sessionProvider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const getUser = async () => {
  const accessToken = cookies().get("USER_SESSION")?.value;
  console.log({ accessToken });
  if (!accessToken) {
    return null;
  }
  const res = await fetch("http://localhost:4000/v1/me", {
    method: "get",
    headers: {
      "Content-Type": "application/json",
      authorization: accessToken,
    },
  });
  const user = await res.json();
  return { user, accessToken };
};

export default async function RootLayout({ children }) {
  const USER = await getUser();
  return (
    <SessionProvider session={USER}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </SessionProvider>
  );
}
